extends:
  - stylelint-config-standard
  - stylelint-config-html/vue
  - stylelint-config-recommended-vue/scss
  - stylelint-config-recommended-scss
overrides:
  - files:
      - "**/*.vue"
    customSyntax: postcss-html