namespace Shimakaze.Client.Kernel.Model.SpawnerConfig;

public sealed class Spawner
{
    public SpawnerSettings Settings { get; } = new SpawnerSettings();
}

public static class SpawnerExtensions
{
    public static Spawner ConfigureSettings(this Spawner builder, Action<SpawnerSettings> setting)
    {
        setting(builder.Settings);
        return builder;
    }

    public static async Task WriteToAsync(this Spawner builder, TextWriter writer)
    {
        await writer.WriteAsync(";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;").ConfigureAwait(false);
        await writer.WriteAsync('\n').ConfigureAwait(false);
        await writer.WriteAsync(";;; Generated by Shimakaze.Client ;;;").ConfigureAwait(false);
        await writer.WriteAsync('\n').ConfigureAwait(false);
        await writer.WriteAsync(";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;").ConfigureAwait(false);
        await writer.WriteAsync('\n').ConfigureAwait(false);
        await writer.WriteAsync('\n').ConfigureAwait(false);

        await builder.Settings.WriteToAsync(writer).ConfigureAwait(false);
    }

}
